### ISSUE TITLE
How long did it take to train your model?

### ISSUE THREAD

**Issue by jianantian** [ProjectNUWA/LayoutNUWA#10]
In the paper, i find that you run all experiments on 64 NVIDIA V100 GPUs. How long did it take to train your model?

**Comment by ZetangForward** [comment]
64GPUs will cost more than 120 hours for training for the large single dataset (PubLayNet and RICI). For the domain-agonist setting, it will cost a week. We recommend pre-training the model on the domain-agonist setting for a few days and continually fine-tuning the model on the special dataset for efficiency and effectiveness.
