### ISSUE TITLE
tried to get lr value before scheduler/optimizer started stepping, returning lr=0

### ISSUE THREAD

**Issue by hangzeli08** [ProjectNUWA/LayoutNUWA#3]
<img width="1439" alt="image" src="https://github.com/ProjectNUWA/LayoutNUWA/assets/104003969/524ea04c-741b-42b6-b441-c90be15d6667">
 
reported this wrong

**Comment by ZetangForward** [comment]
Hi, according to my experience, this is directly related to the platform and GPU model you are using, as the installation of the Deepspeed package may fail.
