### ISSUE TITLE
Sample for inference data file

### ISSUE THREAD

**Issue by dittops** [ProjectNUWA/LayoutNUWA#5]
Is there a sample data file for the inference script?

I have tried the `LayoutNUWA/data/rico25-max25/html_format/test_numerical.jsonl` but seems that's not the right format.

**Comment by dittops** [comment]
I have tried updating the generate.py file with the following 

```python
# cond_cate_to_size_pos = samples.get("cond_cate_to_size_pos_seq_modeling")[0]
# cond_cate_size_to_pos = samples.get("cond_cate_size_to_pos_seq_modeling")[0]
# cond_recover_mask_input = samples.get("cond_recover_mask_seq_modeling")[0]
cond_cate_to_size_pos = samples["cond_cate_to_size_pos_input_seqs"]
cond_cate_size_to_pos = samples["cond_cate_size_to_pos_input_seqs"]
cond_recover_mask_input = samples["cond_recover_mask_input_seqs"]
```

But while running the script with the test_numerical.jsonl file on an A100 I'm getting OOM. Any thought on what might be the issue?

**Comment by ZetangForward** [comment]
Sorry for the late reply. There are some redundant codes in this version of the code (for ablation experiments), resulting in incorrect data format generated. Please refer to the paper for some modifications, and we will also update the code library later.
We used the settings of V100 and FP16 for inference without OOM. You can check the output length and sampling strategy of the model to see if they are consistent with this version of the code.
