### ISSUE TITLE
May I ask why use <FILL_x>  instead of <MASK>，Why not just use <MASK>？

### ISSUE THREAD

**Issue by hangzeli08** [ProjectNUWA/LayoutNUWA#6]

**Comment by ZetangForward** [comment]
Hi, this is just a placeholder selection. We want to use <Fill_ i> to tell the model that the i-th position needs to be filled. Previous work has shown that displaying the semantics of informing model placeholders can improve the effectiveness of model-filling [https://arxiv.org/abs/2201.07520](https://arxiv.org/abs/2201.07520).

**Comment by hangzeli08** [comment]
nice answer，nice work。Thank you for your reply
