### ISSUE TITLE
Request for Pre-trained Model for FID on Magazine Dataset

### ISSUE THREAD

**Issue by iwa-shi** [ProjectNUWA/LayoutNUWA#7]
Hi, @ZetangForward 

Your research is quite interesting!
I'm trying to compare your results with my method, and it would be beneficial if you could share the pre-trained model you used for calculating FID on the **Magazine** dataset.

If, for any reason, you cannot share the model, could you provide details about the hyperparameters you used during the training of FID model? We followed the [LayoutDM](https://github.com/CyberAgentAILab/layout-dm/blob/main/docs/custom_dataset.md) guidelines for training the FID model, but we haven't achieved the results we were aiming for.

Thank you in advance for your time and consideration!

**Comment by ZetangForward** [comment]
Hello, Thank you for your understanding. I followed this [guideline](https://github.com/ktrk115/const_layout) to preprocess the Magazine data and train the FID model by following LayoutDM. What `` hyperparameters`` do you need? I will provide them if possible.

**Comment by iwa-shi** [comment]
Thank you for your swift response!

I'd like to clarify a couple of points:

- Did you use this [code in LayoutDM](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/fid/train.py) to train the FID model?
- Were the hyperparameters used for training consistent with the default values in this code? Specifically, did you use `batch_size=64`, `iteration=200,000`, and `lr=3e-4`?

**Comment by ZetangForward** [comment]
> Thank you for your swift response!
> 
> I'd like to clarify a couple of points:
> 
> * Did you use this [code in LayoutDM](https://github.com/CyberAgentAILab/layout-dm/blob/main/src/trainer/trainer/fid/train.py) to train the FID model?
> * Were the hyperparameters used for training consistent with the default values in this code? Specifically, did you use `batch_size=64`, `iteration=200,000`, and `lr=3e-4`?

Yes, I use this code for LayoutDM.
I set batch_size as 512, iteration=200,000, and lr=3e-4

**Comment by iwa-shi** [comment]
Thank you for sharing. I will try again using the parameters you provided.
Appreciate your assistance!
