### ISSUE TITLE
Regarding Table1, 2 in your paper

### ISSUE THREAD

**Issue by AtsukiOsanai** [ProjectNUWA/LayoutNUWA#8]
Thank you for sharing a great work!

I have a question about the Table1 and 2 in your paper. You compare your proposed method with 6 baselines including `LayoutTransformer`, `BLT`, `LayoutGAN++`, `MaskGIT`, `DiffusionLM`, and `LayoutDM`. Except for `LayoutGAN++`, other methods would be trained on `unconditional` setting in the original setting. Did you extend them to a `category-conditional` training to compare results with `LayoutNUWA`?  Or did you get `category-conditional` results from `unconditional` trained models?

**Comment by ZetangForward** [comment]
Thanks for your attention to our work. For those models, we specifically extend them to a ``category-conditional`` training with LayoutDM scripts.

**Comment by AtsukiOsanai** [comment]
@ZetangForward 
I appreciate your reply.
I could understand clearly.
